# Generated by Django 5.2.8 on 2025-11-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chatmessage_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.conversation')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.document')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
